#!/etc/bin/env bash

#benummert de regels van een ingevoerd .txt bestand

if [ -z "$1" ]; then
    echo "No file specified"
else

#telt het aantal regels
REGELS=$(wc -l < $1)

#for loop telt af anders klopt de nummering niet
for ((i=$REGELS;i>0;i--)); do
    if (($i % 100 == 0)); then
        #voert regelnummer (en newline) in op de juiste regel via sed
        sed -i "$i i ============== Regel $i ==============\n" $1
    fi
done

fi
