#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No directory specified"
else

#converteert alle .jpg bestanden naar .png bestanden
#met een maximale grote van 128x128 en geeft ze de juiste bestandsnaam
for file in $(find $1 -name *.jpg); do
    magick convert -resize '128x128' $file ${file:0:-4}.png
    rm $file
done

fi
